"""initial schema

Revision ID: f4b11843e38e
Revises: 
Create Date: 2026-08-13 14:54:10.366727
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4b11843e38e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch', sa.String(length=16), nullable=False),
    sa.Column('season', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('realm', sa.String(length=96), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('class_key', sa.String(length=40), nullable=False),
    sa.Column('spec_key', sa.String(length=40), nullable=False),
    sa.Column('simc_text', sa.Text(), nullable=True),
    sa.Column('current_item_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'realm', 'region')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('game_item_id', sa.BigInteger(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_zh_cn', sa.String(length=255), nullable=True),
    sa.Column('slot_key', sa.String(length=32), nullable=False),
    sa.Column('armor_type', sa.String(length=20), nullable=True),
    sa.Column('weapon_type', sa.String(length=32), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('max_sockets', sa.Integer(), nullable=False),
    sa.Column('is_crafted', sa.Boolean(), nullable=False),
    sa.Column('is_tier', sa.Boolean(), nullable=False),
    sa.Column('has_special_effect', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['game_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'game_item_id')
    )
    op.create_table('specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('class_key', sa.String(length=40), nullable=False),
    sa.Column('spec_key', sa.String(length=40), nullable=False),
    sa.Column('class_name_zh_cn', sa.String(length=40), nullable=False),
    sa.Column('spec_name_zh_cn', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('mastery_coefficient', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rules_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['game_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'class_key', 'spec_key')
    )
    op.create_table('bis_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=24), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_updated', sa.String(length=32), nullable=True),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('instance_name_en', sa.String(length=255), nullable=True),
    sa.Column('instance_name_zh_cn', sa.String(length=255), nullable=True),
    sa.Column('encounter_name_en', sa.String(length=255), nullable=True),
    sa.Column('encounter_name_zh_cn', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_variants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('upgrade_track', sa.String(length=20), nullable=True),
    sa.Column('upgrade_rank', sa.Integer(), nullable=True),
    sa.Column('item_level', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intellect', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('critical_strike', sa.Integer(), nullable=False),
    sa.Column('haste', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Integer(), nullable=False),
    sa.Column('versatility', sa.Integer(), nullable=False),
    sa.Column('sockets', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'item_level')
    )
    op.create_table('loadouts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('patch', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=24), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_stats_json', sa.JSON(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=True),
    sa.Column('calculated_stats_json', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=24), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('values_json', sa.JSON(), nullable=False),
    sa.Column('is_recommended_spec', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['spec_id'], ['specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_id', 'content_type', 'target_type')
    )
    op.create_table('bis_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('slot_key', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['bis_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'slot_key', 'position')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('loadout_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loadout_id'], ['loadouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loadout_consumables',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('loadout_id', sa.BigInteger(), nullable=False),
    sa.Column('consumable_type', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['loadout_id'], ['loadouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loadout_id', 'consumable_type')
    )
    op.create_table('loadout_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('loadout_id', sa.BigInteger(), nullable=False),
    sa.Column('slot_key', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('item_level', sa.Integer(), nullable=False),
    sa.Column('upgrade_track', sa.String(length=20), nullable=True),
    sa.Column('upgrade_rank', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('max_sockets_snapshot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loadout_id'], ['loadouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loadout_id', 'slot_key')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=96), nullable=True),
    sa.Column('tool_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loadout_gems',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('loadout_item_id', sa.BigInteger(), nullable=False),
    sa.Column('socket_index', sa.Integer(), nullable=False),
    sa.Column('gem_item_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['loadout_item_id'], ['loadout_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loadout_item_id', 'socket_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loadout_gems')
    op.drop_table('chat_messages')
    op.drop_table('loadout_items')
    op.drop_table('loadout_consumables')
    op.drop_table('chat_sessions')
    op.drop_table('bis_items')
    op.drop_table('stat_recommendations')
    op.drop_table('loadouts')
    op.drop_table('item_variants')
    op.drop_table('item_sources')
    op.drop_table('bis_profiles')
    op.drop_table('specs')
    op.drop_table('items')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('game_versions')
    # ### end Alembic commands ###

